# Generated by Django 2.1.2 on 2019-02-18 06:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sample_1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_10',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_4',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_5',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_6',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_7',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_8',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_9',
        ),
        migrations.AddField(
            model_name='item',
            name='customer_address',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='住所'),
        ),
        migrations.AddField(
            model_name='item',
            name='customer_kana',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='カナ'),
        ),
        migrations.AddField(
            model_name='item',
            name='customer_memo',
            field=models.TextField(blank=True, null=True, verbose_name='メモ'),
        ),
        migrations.AddField(
            model_name='item',
            name='customer_name',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='名前'),
        ),
        migrations.AddField(
            model_name='item',
            name='customer_post_code',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999)], verbose_name='郵便番号'),
        ),
        migrations.AddField(
            model_name='item',
            name='customer_tel_number',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='電話番号'),
        ),
        migrations.AddField(
            model_name='item',
            name='customer_timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='タイムスタンプ'),
        ),
    ]
