# Generated by Django 2.1.2 on 2019-02-18 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190218_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'ひと目でわかる顧客情報', 'verbose_name_plural': 'ひと目でわかる顧客情報'},
        ),
    ]
